-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  role text check (role in ('admin', 'client')) default 'client',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for products
create table products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric,
  image_url text,
  status text check (status in ('available', 'sold')) default 'available',
  category text, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for products
alter table products enable row level security;

-- Create policies for products
create policy "Products are viewable by everyone." on products
  for select using (true);

create policy "Only admins can insert products." on products
  for insert with check (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Only admins can update products." on products
  for update using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Only admins can delete products." on products
  for delete using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Create a table for static content (text editing)
create table static_content (
  key text primary key,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for static_content
alter table static_content enable row level security;

-- Create policies for static_content
create policy "Static content is viewable by everyone." on static_content
  for select using (true);

create policy "Only admins can insert static content." on static_content
  for insert with check (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create policy "Only admins can update static content." on static_content
  for update using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- Storage policies (bucket must be created manually in dashboard called 'images')
-- You typically set these in the Storage UI, but here is the logic:
-- SELECT: Public
-- INSERT/UPDATE/DELETE: specific to admin role check as above.
