-- Migration: Add Features (Messages, Appointments, Reviews)
-- Run this in Supabase SQL Editor

-- 1. MESSAGES TABLE (Contact & Quotes)
CREATE TABLE IF NOT EXISTS messages (
    id bigint generated by default as identity primary key,
    sender_name text not null,
    sender_email text not null,
    subject text,
    content text,
    type text check (type in ('contact', 'quote')),
    status text check (status in ('unread', 'read', 'replied')) default 'unread',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can insert messages." ON messages
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Admins can view messages." ON messages
    FOR SELECT USING (
        exists (
            select 1 from profiles
            where profiles.id = auth.uid() and profiles.role = 'admin'
        )
    );

CREATE POLICY "Admins can update messages." ON messages
    FOR UPDATE USING (
        exists (
            select 1 from profiles
            where profiles.id = auth.uid() and profiles.role = 'admin'
        )
    );

-- 2. APPOINTMENTS TABLE
CREATE TABLE IF NOT EXISTS appointments (
    id bigint generated by default as identity primary key,
    client_name text not null,
    client_email text not null,
    client_phone text,
    requested_date timestamp with time zone not null,
    message text,
    status text check (status in ('pending', 'confirmed', 'cancelled')) default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Appointments
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can request appointments." ON appointments
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Admins can view/manage appointments." ON appointments
    FOR ALL USING (
        exists (
            select 1 from profiles
            where profiles.id = auth.uid() and profiles.role = 'admin'
        )
    );
    
-- Allow users to see their own appointments (optional, if logged in)
CREATE POLICY "Users can see own appointments." ON appointments
    FOR SELECT USING (
        client_email = (select email from profiles where id = auth.uid())
    );


-- 3. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS reviews (
    id bigint generated by default as identity primary key,
    author_name text not null,
    rating integer check (rating >= 1 and rating <= 5),
    comment text,
    is_approved boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Reviews
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read approved reviews." ON reviews
    FOR SELECT USING (is_approved = true);

CREATE POLICY "Admins can read all reviews." ON reviews
    FOR SELECT USING (
        exists (
            select 1 from profiles
            where profiles.id = auth.uid() and profiles.role = 'admin'
        )
    );

CREATE POLICY "Authenticated users can submit reviews." ON reviews
    FOR INSERT WITH CHECK (auth.role() = 'authenticated'); 
    -- Or allow everyone: FOR INSERT WITH CHECK (true);

CREATE POLICY "Admins can update/approve reviews." ON reviews
    FOR UPDATE USING (
        exists (
            select 1 from profiles
            where profiles.id = auth.uid() and profiles.role = 'admin'
        )
    );

CREATE POLICY "Admins can delete reviews." ON reviews
    FOR DELETE USING (
        exists (
            select 1 from profiles
            where profiles.id = auth.uid() and profiles.role = 'admin'
        )
    );
